# Generated by Django 6.0.3 on 2026-03-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
